### ISSUE TITLE
Endbearbeitung DaZ-Handbuch (Steffi)

### ISSUE THREAD

**Issue by chrisreuter** [chrisreuter/dazhandbuch#29]
## E-Mail 2017-01-13 Steffi; ergänzt durch E-Mail 2017-01-30 Steffi

> 7 Aktualisierungen vornehmen bis: Dienstag 31. Januar 18 Uhr [E-Mail 2017-01-13 Steffi]:

- [x] Umstellung der Schrift auf AEWB-Grün #33 
- [x]  Verschieben der Spielebücher unter den Punkt „Spiele“ #32 
- [x] Korrektur NQL zu NLQ [s. #28  ]
- [x] NEU: Verschieben des Glossars unter „Praxistipps“ als Punkt 0.4 #30 
- [x] Einstellen der Texte Deutsch für den Beruf [E-Mail 2017-01-30 v. Steffi in Klammern gesetzt (*)] #27 
- [ ] (Einstellen der Texte Prüfungsvorbereitung) [E-Mail 2017-01-30 v. Steffi in Klammern gesetzt (*)]
- [x] Einstellen aller fehlenden Bilder [teilweise erledigt und mit E-Mail vom 2017-01-30 von SH gestrichen]
- [x] WICHTIG: Kontakt-Link („Technische Fragen“) zu Christian entfernen! [ergänzt in E-Mail vom 2017-01-30 Steffi]

> (*) die beiden Punkte sind Streitpunkte, zu denen ich einfach keinen Nerv mehr habe, bitte entscheidet Ihr, ob Ihr das noch schaffen könnt. [E-Mail 2017-01-30 Steffi]

**Comment by chrisreuter** [comment]
## E-Mail 31.01.2017 Steffi

Da ich bisher keine Rückmeldung von Euch zu dieser Liste erhalten hatte, gehe ich davon aus, dass alles soweit klar und morgen alles fertig gestellt sein wird. Auch die Hoffnung, dass morgen bei den Webseiten und APPs jeweils mehr als zwei Empfehlungen stehen werden, habe ich noch nicht ganz aufgegeben….
 
Hier noch einmal die To-Do-Liste:
-  Umstellung der Schrift auf AEWB-Grün
-  Verschieben der Spielebücher unter den Punkt „Spiele“
-  Korrektur NQL zu NLQ
-  NEU: Verschieben des Glossars unter „Praxistipps“ als Punkt 0.4
-  (Einstellen der Texte Deutsch für den Beruf (die seit Ende Oktober bei Euch sind) )
-  (Einstellen der Texte Prüfungsvorbereitung)
-  Einstellen aller fehlenden Bilder
 
WICHTIG: Bitte entfernt ferner aus dem Impressum bis spätestens morgen 18 Uhr auch den Kontakt-Link („Technische Fragen“), der zu Christian führt!

**Comment by chrisreuter** [comment]
## E-Mail 31.01.2017 Steffi

Da ich bisher keine Rückmeldung von Euch zu dieser Liste erhalten hatte, gehe ich davon aus, dass alles soweit klar und morgen alles fertig gestellt sein wird. Auch die Hoffnung, dass morgen bei den Webseiten und APPs jeweils mehr als zwei Empfehlungen stehen werden, habe ich noch nicht ganz aufgegeben….
 
Hier noch einmal die To-Do-Liste:
-  Umstellung der Schrift auf AEWB-Grün
-  Verschieben der Spielebücher unter den Punkt „Spiele“
-  Korrektur NQL zu NLQ
-  NEU: Verschieben des Glossars unter „Praxistipps“ als Punkt 0.4
-  (Einstellen der Texte Deutsch für den Beruf (die seit Ende Oktober bei Euch sind) )
-  (Einstellen der Texte Prüfungsvorbereitung)
-  Einstellen aller fehlenden Bilder
 
WICHTIG: Bitte entfernt ferner aus dem Impressum bis spätestens morgen 18 Uhr auch den Kontakt-Link („Technische Fragen“), der zu Christian führt!
