### ISSUE TITLE
Umstellung der Schrift auf AEWB-Grün (Steffi)

### ISSUE THREAD

**Issue by chrisreuter** [chrisreuter/dazhandbuch#33]
## E-Mail Steffi Erinnerung

- [x] SCSS checken
- [x] highlight--text color durch AEWB color #00847d ersetzen
- [x] navigatio-header a:hover color durch AEWB color #00847d ersetzen
- [x] navigatio-footer a:hover color durch AEWB color #00847d ersetzen
- [x] page-content a:hover color durch AEWB color #00847d ersetzen
- [x] error-content a:hover color durch AEWB color #00847d ersetzen

- [x] Nachkontrolle
